version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./forum:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/liv/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./forum:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - backend
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./forum:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend
  npm:
    image: node:latest
    container_name: node
    volumes:
      - ./forum:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./forum:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - backend